import sys
from pathlib import Path
from moviepy import (
    VideoFileClip, ImageClip, CompositeVideoClip, concatenate_videoclips, AudioFileClip, ColorClip, CompositeAudioClip
)
from moviepy.video.fx import Loop
from moviepy.audio.fx import MultiplyVolume, AudioFadeIn, AudioFadeOut

# Process video clip: loops or trims, mutes, crops to centered vertical, and applies dynamic zoom
def process_clip_with_zoom(clip_path, duration, target_w=1080, target_h=1920, zoom_ratio=1.10):
    clip = VideoFileClip(clip_path)
    
    if clip.duration < duration:
        clip = clip.with_effects([Loop(duration=duration)])
    else:
        clip = clip.subclipped(0, duration)
        
    clip = clip.without_audio()
    w, h = clip.size
    
    scale_factor = max(target_w / w, target_h / h)
    resize_func = lambda t: scale_factor * (1.0 + (zoom_ratio - 1.0) * (t / duration))
    resized_clip = clip.resized(resize_func)
    
    pos_func = lambda t: (
        int((target_w - w * scale_factor * (1.0 + (zoom_ratio - 1.0) * (t / duration))) / 2),
        int((target_h - h * scale_factor * (1.0 + (zoom_ratio - 1.0) * (t / duration))) / 2)
    )
    
    comp_clip = CompositeVideoClip(
        [resized_clip.with_position(pos_func)],
        size=(target_w, target_h)
    ).with_duration(duration)
    
    return comp_clip

# Build intermediate video clips from the storyboard scene list
def build_video_clips(storyboard, assets_dir, hook_slides, cta_slide_path):
    clips = []
    for scene in storyboard.scenes:
        sid = scene.id
        dur = scene.est_duration
        stype = scene.type
        
        print(f"Processing Scene {sid} ({stype}, {dur:.2f}s)...")
        
        if stype == "hook_black":
            # Three stage slide transition for the hook
            c1 = ImageClip(hook_slides[0]).with_duration(0.8)
            c2 = ImageClip(hook_slides[1]).with_duration(0.8)
            c3 = ImageClip(hook_slides[2]).with_duration(max(0.1, dur - 1.6))
            clips.append(concatenate_videoclips([c1, c2, c3]))
            
        elif stype == "cta_black":
            clips.append(ImageClip(cta_slide_path).with_duration(dur))
            
        elif stype == "stock_video":
            clip_path = assets_dir / f"scene_{sid}.mp4"
            if clip_path.exists():
                clips.append(process_clip_with_zoom(str(clip_path), dur, target_w=1080, target_h=1920, zoom_ratio=1.10))
            else:
                print(f"Warning: Stock video scene_{sid}.mp4 not found. Creating placeholder.")
                clips.append(ColorClip(size=(1080, 1920), color=(0, 0, 0)).with_duration(dur))
                
        elif stype == "reuse_video":
            clip_path = assets_dir / f"scene_{scene.reuse_scene_id}.mp4"
            if clip_path.exists():
                clips.append(process_clip_with_zoom(str(clip_path), dur, target_w=1080, target_h=1920, zoom_ratio=1.10))
            else:
                print(f"Warning: Reusable stock video scene_{scene.reuse_scene_id}.mp4 not found. Creating placeholder.")
                clips.append(ColorClip(size=(1080, 1920), color=(0, 0, 0)).with_duration(dur))
                
        elif stype == "split_screen":
            left_path = assets_dir / f"scene_{sid}_left.mp4"
            right_path = assets_dir / f"scene_{sid}_right.mp4"
            
            if left_path.exists() and right_path.exists():
                left_clip = process_clip_with_zoom(str(left_path), dur, target_w=540, target_h=1920, zoom_ratio=1.10)
                right_clip = process_clip_with_zoom(str(right_path), dur, target_w=540, target_h=1920, zoom_ratio=1.10)
                
                left_positioned = left_clip.with_position((0, 0))
                right_positioned = right_clip.with_position((540, 0))
                
                split_comp = CompositeVideoClip([left_positioned, right_positioned], size=(1080, 1920))
                clips.append(split_comp)
            else:
                print(f"Warning: Split screen files not found. Creating placeholder.")
                clips.append(ColorClip(size=(1080, 1920), color=(0, 0, 0)).with_duration(dur))
    return clips

# Mix audio and write the final file using MoviePy
def mix_audio_and_render(clips, voiceover_mp3, bgm_path, storyboard, total_duration, output_path):
    print("Concatenating video clips...")
    final_video = concatenate_videoclips(clips, method="compose")
    
    # Audio Processing and Mixing
    print("\nMixing Audio...")
    voice_track = AudioFileClip(str(voiceover_mp3))
    bgm_raw = AudioFileClip(str(bgm_path))
    
    # Calculate BGM switch times (defaults to 25.16s if not generated by LLM)
    beat_switch = storyboard.bgm_beat_switch_time if storyboard.bgm_beat_switch_time else 25.16
    bgm_vol = storyboard.bgm_volume if storyboard.bgm_volume else 0.08
    
    # BGM 1 (Problem theme): Plays from 1.8s to (beat_switch + 1.3s) for cross-fade
    bgm1_start = 1.8
    bgm1_end = beat_switch + 1.3
    bgm1_dur = bgm1_end - bgm1_start
    bgm1_cut = bgm_raw.subclipped(0, bgm1_dur)
    bgm1_mixed = bgm1_cut.with_effects([
        MultiplyVolume(bgm_vol),
        AudioFadeIn(1.5),
        AudioFadeOut(2.5)
    ]).with_start(bgm1_start)
    
    # BGM 2 (Solution theme): Starts at beat_switch of video (using BGM offset 35.0s)
    bgm2_start = beat_switch
    bgm2_end = total_duration - 1.70  # fade out before the CTA black screen
    bgm2_dur = bgm2_end - bgm2_start
    bgm2_cut = bgm_raw.subclipped(35.0, 35.0 + bgm2_dur)
    bgm2_mixed = bgm2_cut.with_effects([
        MultiplyVolume(bgm_vol),
        AudioFadeIn(2.0),
        AudioFadeOut(2.5)
    ]).with_start(bgm2_start)
    
    final_audio = CompositeAudioClip([voice_track, bgm1_mixed, bgm2_mixed])
    final_video = final_video.with_audio(final_audio)
    
    print(f"\nRendering final video to {output_path}...")
    try:
        final_video.write_videofile(
            str(output_path),
            fps=30,
            codec="libx264",
            audio_codec="aac",
            temp_audiofile="temp-audio-mixed.m4a",
            remove_temp=True
        )
        print(f"\nSUCCESS! Reel rendered successfully at: {output_path.absolute()}")
    except Exception as e:
        print(f"Error rendering video: {e}")
        raise e
    finally:
        final_video.close()
        for c in clips:
            c.close()
